# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/msc-quantum-magnetic-2024',
                'doc_host': 'https://andreamunafo.github.io',
                'git_url': 'https://github.com/andreamunafo/msc-quantum-magnetic-2024',
                'lib_path': 'msc_quantum_magnetic_2024'},
  'syms': { 'msc_quantum_magnetic_2024.core': { 'msc_quantum_magnetic_2024.core.foo': ( 'core.html#foo',
                                                                                        'msc_quantum_magnetic_2024/core.py')}}}
